APP:
  version: v1.0
  sn: "0" 
  uuid: 123e4567-e89b-12d3-a456-426614174000
  passwd: "123456"
  label: 123e4567-e89b-12d3-a456-426614174000
  
MYSQL:
  dsn: "root:123456@tcp(127.0.0.1:3306)/iot-collector-server?charset=utf8mb4&parseTime=True&loc=Local"
  
REDIS:
  ip: 127.0.0.1
  post: 6379
  passwd: ""
  database: 2
 
Influxdb :
  enable: true
  url : "http://127.0.0.1:8086"
  token : "YgJqi_kS9zx2e_G4d514f9IAU_LNM8O5iSFXwzckJqEiW_d8x4hni3rMpoO4dThCIhdBPhseyaBKS-Cvb_8bsg=="
  org : "group1"
  bucket : "my1"
  write_timeout: 5000        # 写入超时（毫秒）
  buffer_size: 1000          # 缓冲区大小
  flush_interval: 1s         # 刷新间隔
  write_quantity_id: 1000000

LOG:
  enable: true
  path: ./logs
  cacheTTL: 30
  flags: Ldate Lmicroseconds Llongfile 

API:
  enable: true
  ip: 0.0.0.0
  post: 8103
  header:
    - key: Access-Control-Allow-Origin
      value: "*"
    - key: Access-Control-Allow-Methods
      value: POST, GET
    - key: Access-Control-Allow-Headers
      value: Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, F_Access_Token, F_Refresh_Token, F_Terminal_Uuid

Mqtt_Rpc:
  example: default
  enable: true
  business_timeout: 5s # 业务处理超时
  listen_topic: /GoEdge-IoT/123e4567-e89b-12d3-a456-426614174000 # 监听主题
  config_service_topic: /GoEdge-IoT/123e4567-e89b-12d3-a456-426614174001 # 配置服务主题

  # 发送mqtt数据
  point_push_value: /GoEdge-IoT/123e4567-e89b-12d3-a456-426614174000/point/push/value # 点位更新
  point_down_value: /GoEdge-IoT/123e4567-e89b-12d3-a456-426614174000/point/issue/value # 点下发值
  point_alarm_value: /GoEdge-IoT/123e4567-e89b-12d3-a456-426614174000/point/alarm/value # 点位报警


Mqtt:
  default:
    enable: true
    broker: tcp://127.0.0.1:1883
    username: o7aKZOj53p2PkkFJzKzM
    password: lpj4VZ4ZYFg5GmINhRat
    client_id:  123e4567-e89b-12d3-a456-426614174000
    clean_session: True # 清洁会话（重启不接收离线消息）
    auto_reconnect: True # 自动重连
    connect_timeout: 10s # 连接超时
    write_timeout: 5s # 写超时
    keep_alive: 30s # 心跳保活

 
ALARM:
  Config_CacheTTL: 1h # 报警配置缓存TTL，0s=永久保存不过期

Config_Service:
  enable: True
  address: "http://127.0.0.1:8102"
