APP:
  version: v1.0
  sn: "0" 
  uuid: 123e4567-e89b-12d3-a456-426614174000
  aes_passwd: "123456"
  
MYSQL:
  dsn: "root:123456@tcp(127.0.0.1:3306)/iot-collector-server-123e4567-e89b-12d3-a456-426614174000?charset=utf8mb4&parseTime=True&loc=Local"
  
REDIS:
  ip: 127.0.0.1
  post: 6379
  passwd: ""
  database: 2
 
Influxdb :
  url : "http://192.168.220.40:8086"
  token : "XGwVLBQDWuqQ5F3l62E_IZ7U1BacqKpYablCj5EWkC3gCoU0SUjfC2K-qemC3TH3g0iJVsJineiSViuUvVgElw=="
  org : "default_group"
  bucket : "my1"

LOG:
  enable: true
  path: ./logs
  cacheTTL: 30
  flags: Ldate Lmicroseconds Llongfile 

user_Service:
  url: "http://127.0.0.1:8101" 
  apikey: "123456"
  secret: "123456"  
 
Mqtt_Rpc:
  broker: tcp://127.0.0.1:1883
  username: o7aKZOj53p2PkkFJzKzM
  password: lpj4VZ4ZYFg5GmINhRat
  client_id:  123e4567-e89b-12d3-a456-426614174000
  clean_session: True
  auto_reconnect: True
  connect_timeout: 10s
  write_timeout: 5s
  keep_alive: 30s
  
  business_timeout: 5s 
  listen_topic: /GoEdge-IoT/123e4567-e89b-12d3-a456-426614174000
  config_service_topic: /GoEdge-IoT/123e4567-e89b-12d3-a456-426614174001 