APP:
  version: v1.0
  sn: "0" 
  uuid: 123e4567-e89b-12d3-a456-426614174001
  aes_passwd: "123456"
  
API:
  ip: 0.0.0.0
  post: 8102
  header:
    - key: Access-Control-Allow-Origin
      value: "*"
    - key: Access-Control-Allow-Methods
      value: POST, GET
    - key: Access-Control-Allow-Headers
      value: Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, F_Access_Token, F_Refresh_Token, F_Terminal_Uuid

MYSQL:
  dsn: "root:123456@tcp(127.0.0.1:3306)/iot-config-service?charset=utf8mb4&parseTime=True&loc=Local"
  
REDIS:
  ip: 127.0.0.1
  post: 6379
  passwd: ""
  database: 2
 
LOG:
  enable: true
  path: ./logs
  cacheTTL: 30s
  flags: Ldate Lmicroseconds Llongfile

 
User_Service:
  url: "http://127.0.0.1:8101" 
  apikey: "123456"
  secret: "123456"
  timeout: 30s 

Mqtt_Rpc:
  broker: tcp://emqx.njtxy.zwf.fan:1883
  username: o7aKZOj53p2PkkFJzKzM
  password: lpj4VZ4ZYFg5GmINhRat
  client_id:  123e4567-e89b-12d3-a456-426614174001
  clean_session: True
  auto_reconnect: True
  connect_timeout: 10s
  write_timeout: 5s
  keep_alive: 30s
  
  business_timeout: 5s 
  listen_topic: /GoEdge-IoT/123e4567-e89b-12d3-a456-426614174001 